[package]
name = "ohs-backend"
version = "0.1.0"
edition = "2024"
authors = ["Emre YILDIZ <emre.yildiz.dev@hotmail.com"]
description = "Multi-tenant Occupational Health and Safety Backend Application"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
dotenv = "0.15.0"
tokio = { version = "1.45.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
