services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: ohs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ohs_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ohs_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ohs_network

  redis:
    image: redis:8.0.0-bookworm
    container_name: ohs_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ohs_network

  coturn:
    image: coturn/coturn:latest
    container_name: ohs_coturn
    restart: unless-stopped
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    # Expose UDP and TCP ports for TURN/STUN
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
      - "49152-49200:49152-49200/udp"
    command: -c /etc/coturn/turnserver.conf -v
    healthcheck:
      test: ["CMD-SHELL", "apt-get update && apt-get install -y net-tools && netstat -tulpn | grep -q 3478 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ohs_network

  ohs-backend:
    build:
      context: ./ # Assuming your Axum app Dockerfile is here
      dockerfile: Dockerfile
    container_name: ohs_backend
    restart: unless-stopped
    ports:
      - "8000:8000" # Assuming your Axum app runs on port 8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      garage:
        condition: service_healthy
      garage-init:
        condition: service_completed_successfully
      coturn:
        condition: service_healthy
    environment:
      # Add any environment variables your Axum app needs
      DATABASE_URL: postgresql://user:password@postgres:5432/ohs_db
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://garage:3900
      S3_ACCESS_KEY_ID: garage-access-key
      S3_SECRET_ACCESS_KEY: garage-secret-key
      S3_BUCKET_NAME: ohs-bucket
      TURN_URL_UDP: turn:coturn:3478?transport=udp
      TURN_URL_TCP: turn:coturn:3478?transport=tcp
      TURN_USERNAME: turnuser
      TURN_PASSWORD: turnpassword
    networks:
      - ohs_network

  garage:
    image: dxflrs/garage:v1.1.0
    container_name: ohs_garage_s3
    restart: unless-stopped
    ports:
      - "3900:3900" # S3 API port
      - "3901:3901" # Cluster internal RPC port
      - "3902:3902" # Cluster internal Raft port
    volumes:
      - ./garage-data:/var/lib/garage
      - ./garage-config/garage.toml:/etc/garage.toml
    entrypoint: ["/garage", "server"]
    environment:
      # These are used for initializing the S3 credentials
      INITIAL_S3_ACCESS_KEY_ID: garage-access-key
      INITIAL_S3_SECRET_ACCESS_KEY: garage-secret-key
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ohs_network

  garage-init:
    image: dxflrs/garage:v1.1.0
    container_name: ohs_garage_init
    depends_on:
      garage:
        condition: service_healthy
    volumes:
      - ./init-garage.sh:/init-garage.sh
      - ./garage-data:/var/lib/garage
      - ./garage-config/garage.toml:/etc/garage.toml
    entrypoint: ["/bin/bash", "/init-garage.sh"]
    networks:
      - ohs_network

volumes:
  postgres-data:
  redis-data:
  garage-data:

networks:
  ohs_network:
    driver: bridge
