services:
  postgres:
    image: postgres:17.5-bookworm
    container_name: ohs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ohs_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ohs_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ohs_network

  redis:
    image: redis:8.0.0-bookworm
    container_name: ohs_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ohs_network

  coturn:
    image: coturn/coturn:latest
    container_name: ohs_coturn
    restart: unless-stopped
    volumes:
      - ./coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
    # Expose UDP and TCP ports for TURN/STUN
    # Ensure these ports are also open on your host firewall
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      # Example relay ports, adjust as per your turnserver.conf
      - "49152-49200:49152-49200/udp"
    # The command depends on your turnserver.conf.
    # This is a basic example, you might need to adjust it.
    # command: -c /etc/coturn/turnserver.conf -L 0.0.0.0
    networks:
      - ohs_network
    # Add healthcheck if coturn image supports it or use a custom script

  ohs-backend:
    build:
      context: ./ # Assuming your Axum app Dockerfile is here
      dockerfile: Dockerfile
    container_name: ohs_backend
    restart: unless-stopped
    ports:
      - "8000:8000" # Assuming your Axum app runs on port 8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      garage:
        condition: service_started # Garage might not have a simple healthcheck
      coturn:
        condition: service_started # Coturn might not have a simple healthcheck
    environment:
      # Add any environment variables your Axum app needs
      DATABASE_URL: postgresql://user:password@postgres:5432/ohs_db
      REDIS_URL: redis://redis:6379
      S3_ENDPOINT: http://garage:3900
      S3_ACCESS_KEY_ID: garage-access-key
      S3_SECRET_ACCESS_KEY: garage-secret-key
      S3_BUCKET_NAME: ohs-bucket
      # TURN_URL_UDP: turn:coturn_ip_or_domain:3478?transport=udp
      # TURN_URL_TCP: turn:coturn_ip_or_domain:3478?transport=tcp
      # TURN_USERNAME: turn_user
      # TURN_PASSWORD: turn_password
    networks:
      - ohs_network

  garage:
    image: dxflrs/garage:latest
    container_name: ohs_garage_s3
    restart: unless-stopped
    ports:
      - "3900:3900" # S3 API port
      - "3901:3901" # Cluster internal RPC port
      - "3902:3902" # Cluster internal Raft port
    volumes:
      - ./garage-data:/var/lib/garage
      # You'll need to configure Garage. This typically involves a config file.
      # - ./garage/garage.toml:/etc/garage.toml:ro
    environment:
      # Garage configuration can be complex and often uses a config file.
      # These are example environment variables, refer to Garage documentation.
      GARAGE_S3_ACCESS_KEY_ID: garage-access-key
      GARAGE_S3_SECRET_ACCESS_KEY: garage-secret-key
      # GARAGE_META_NODES: "garage:3902" # Example for single node, adjust for cluster
      # GARAGE_DATA_NODES: "garage:3901" # Example for single node, adjust for cluster
      # GARAGE_RPC_BIND_ADDR: "0.0.0.0:3901"
      # GARAGE_RAFT_BIND_ADDR: "0.0.0.0:3902"
      # GARAGE_S3_BIND_ADDR: "0.0.0.0:3900"
      # GARAGE_S3_PUBLIC_HOSTNAME: "localhost:3900" # Or your domain
    # command: garage server -c /etc/garage.toml # If using a config file
    networks:
      - ohs_network

volumes:
  postgres-data:
  redis-data:
  garage-data:
  # coturn-config: # If you prefer named volume for coturn config

networks:
  ohs_network:
    driver: bridge